### ISSUE TITLE
time to train the model and how to use it for new cases

### ISSUE THREAD

**Issue by yr18** [mveres01/pytorch-drl4vrp#2]
Hello,

I try to train the model but it took a very long time to finish. I wonder what is the final result after the training process. Will it give me a trained model? How can I use this model to calculate my case? For example 100 cities with given demands and their longitude and latitude.

Thank you very much!

**Comment by mveres01** [comment]
Hello,

It likely took a while as you are training with a large number of cities. I've updated the README with some training times that I get. A possible thing you can try is training on a task with a smaller number of cities, and then using those weights to test on a task with a larger number of cities. 

There's an example for how to load previously trained weights & apply them to a new task in the README as well

**Comment by yr18** [comment]
Thank you so much for your reply! Thank you so much for your source code too! I am trying to apply this model to solve my case.  However, I have encountered several problems. I will pose some more issues about the case later.

**Comment by mveres01** [comment]
Okay, great, closing this issue then
